###############################################################################
#
#    Service Config section
#
###############################################################################
server:
  port: "9000,9001"
  ip: "127.0.0.1,localhost,192.168.1.103"
  mode: debug  # debug;release

###############################################################################
#
#    Dgraph Config section
#
###############################################################################
dgraph:
  host: "127.0.0.1:9080"

